title: Rebeca Morais aka Rebs | Tech Hub
description: "Engenharia de Software"
url: "https://rebecamorais.github.io"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
